tst_mcs: [8, 16, 64]

_optim:
  - name: Adam
    args:
      lr: 0.1
      amsgrad: yes
  - name: Adam
    args:
      lr: 0.05
      amsgrad: yes
  - name: Adam
    args:
      lr: 0.005
      amsgrad: yes
  - name: Rprop
    args:
      lr: 0.05
  - name: Rprop
    args:
      lr: 0.005
  - name: RMSprop
    args:
      lr: 0.05
      momentum: 0.5
  - name: RMSprop
    args:
      lr: 0.01
      momentum: 0.5
  - name: RMSprop
    args:
      lr: 0.005
      momentum: 0.5